### ISSUE TITLE
关于功能的一些疑问

### ISSUE THREAD

**Issue by junko2013** [HuLaSpark/HuLa#14]
<img width="960" alt="image" src="https://github.com/user-attachments/assets/eee983d8-7195-4bfa-95d4-58a899fc0933">
我已将后端服务运行起来，并且也通过微信扫码登录了，但是似乎加好友功能那些点击都没反应，与项目介绍的预览图有差异，是还有收费版本的吗？

**Comment by nongyehong** [comment]
v1.5版本用的是mock的数据，后面1.6版本之后都是请求后端的数据，你需要去自己下载一下我后端的项目部署来获取数据，我现在暂时没有部署服务器

**Comment by nongyehong** [comment]
添加好友功能暂时前端没有做，但是后端实现了功能

**Comment by nongyehong** [comment]
已完成，查看#https://github.com/HuLaSpark/HuLa/commit/7b530297ac37122ead00a15864e16a73a5547d04
