### ISSUE TITLE
[feat] 软件内自动更新功能

### ISSUE THREAD

**Issue by luyuan2002** [HuLaSpark/HuLa#28]
### 描述问题

目前的更新方案是需要到浏览器手动下载安装包

### 描述您想要的解决方案

是否可以软件内直接更新

**Comment by nongyehong** [comment]
刚好，我们刚在新发布的v2.5.0版本新增了这个功能

**Comment by nongyehong** [comment]
因为是v2.5.0新增的功能，但是v2.4.0功能没有，所以现在你安装就是最新的，你可以手动去修改版本号就可以测试，修改以下版本文件
![image](https://github.com/user-attachments/assets/9c27dcb8-69a4-47be-afb1-f9f3a3ca902d)
