### ISSUE TITLE
[bug] 首次启动直接用测试账号登录会崩溃

### ISSUE THREAD

**Issue by monotone** [HuLaSpark/HuLa#29]
### 📌 Version

v2.5.0

### 💻 Operating System

macOS

### 🐛 Bug Description

用2.5.0 替换上一个版本后首次启动直接用测试账号登录会崩溃：
![image](https://github.com/user-attachments/assets/1d9676ca-b1a6-4c3d-859b-78e0287e3a3f)

### ☄️ intact `tauri info` output

```text
（如果我只是个普通用户，我怎么会有tauri这个命令）
```

**Comment by ZOL4789** [comment]
清理下浏览器缓存试试

**Comment by nongyehong** [comment]
通过升级wry版本可能已经解决类似启动崩溃的情况，更新最新修订版本2.5.2试试

**Comment by nongyehong** [comment]
已修复，#https://github.com/HuLaSpark/HuLa/commit/fefa2f970305839064764cd1d82a0d8e557f3148
